#!/bin/bash
set -euxo pipefail
IFS=$'\n\t'

brew bundle install --file=/Users/remi/.yadm/Brewfile 

# setup oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" "" --unattended
yadm checkout HEAD -- ~/.zshrc
chsh -s $(which zsh)



