#!/bin/bash
set -euxo pipefail
IFS=$'\n\t'

# setup oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" "" --unattended
yadm checkout HEAD -- ~/.zshrc
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
chsh -s $(which zsh)

# packages
brew bundle install --file=/Users/remi/.yadm/Brewfile 



